### ISSUE TITLE
안녕하세요 몇가지 질문드립니다.

### ISSUE THREAD

**Issue by WonTaeJang** [dev-nine2021/recruit#1]
1. 버튼 클릭 이벤트는 구현안해도 되는건가요? 
2. HOT키워드 TOP20 을 제외한 나머지 데이터는 알아서 넣으면 되는걸까요? (이미지에 나온대로만)
3. 웹 프레임워크는 어떤것을 해도 상관없나요? (Vanilla Javascript, react등)

답변 부탁드립니다. :)

**Comment by dev-nine2021** [comment]
@WonTaeJang  :+1::heart:

1. 버튼 클릭 이벤트는 구현안해도 되는건가요?
--> 네 이벤트는 구현 안해도 됩니다.

3. HOT키워드 TOP20 을 제외한 나머지 데이터는 알아서 넣으면 되는걸까요? (이미지에 나온대로만)
--> 네 TOP20 만 첨부된 json 파일 사용 해주세요~

4. 웹 프레임워크는 어떤것을 해도 상관없나요? (Vanilla Javascript, react등)
--> 네 자신이 가장 자신있어하는 웹 프레임워크 사용 하시면 됩니다.
